# Generated by Django 4.0.6 on 2023-04-19 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(15)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
