# Generated by Django 4.0.6 on 2023-04-23 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=30)),
                ('IPFS', models.FileField(upload_to='IPFS/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'rtf', 'txt'])])),
            ],
        ),
    ]
