# Generated by Django 4.0.6 on 2023-05-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_first_name_alter_user_gmail_passwords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gmail_passwords',
            new_name='gmail_password',
        ),
    ]
