# Generated by Django 4.0.6 on 2023-05-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_first_name_alter_user_gmail_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='IPFS',
        ),
        migrations.RemoveField(
            model_name='email',
            name='content',
        ),
        migrations.RemoveField(
            model_name='email',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sender',
        ),
        migrations.AddField(
            model_name='email',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='cid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
