# Generated by Django 4.0.6 on 2023-05-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_email_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='products/default.png', upload_to='products/'),
        ),
    ]
